<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CP Barcode Manager for Vigo</AssemblyName>
    <RootNamespace>CPBarcodeManagerForVigo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.10" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.12" />
  </ItemGroup>
</Project>
